/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazcalculadora;

/**
 *
 * @author pamelamurillo
 */
public class CalculadoraProgramacion extends javax.swing.JDialog {

    /**
     * Creates new form CalculadoraProgramacion
     */
    public CalculadoraProgramacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        optDecimalBase.setSelected(true);
        optDecimalResult.setSelected(true);
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optMultiplicacion1 = new javax.swing.JRadioButton();
        optDivision1 = new javax.swing.JRadioButton();
        optSuma1 = new javax.swing.JRadioButton();
        optResta1 = new javax.swing.JRadioButton();
        grupoBase = new javax.swing.ButtonGroup();
        grupoResultado = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        equal = new javax.swing.JLabel();
        lblResultado = new javax.swing.JTextField();
        btnRealizarOperacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        optHexadecimalBase = new javax.swing.JRadioButton();
        optDecimalBase = new javax.swing.JRadioButton();
        optBinarioBase = new javax.swing.JRadioButton();
        optOctalBase = new javax.swing.JRadioButton();
        lblBase = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        optHexadecimalResult = new javax.swing.JRadioButton();
        optDecimalResult = new javax.swing.JRadioButton();
        optBinarioResult = new javax.swing.JRadioButton();
        optOctalResult = new javax.swing.JRadioButton();

        optMultiplicacion1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optMultiplicacion1.setText("Multiplicación");
        optMultiplicacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMultiplicacion1ActionPerformed(evt);
            }
        });

        optDivision1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optDivision1.setText("División");
        optDivision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDivision1ActionPerformed(evt);
            }
        });

        optSuma1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optSuma1.setText("Suma");
        optSuma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSuma1ActionPerformed(evt);
            }
        });

        optResta1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optResta1.setText("Resta");
        optResta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optResta1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Pamela Murillo Anchia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        equal.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        equal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equal.setText("=");
        equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equal, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblResultado.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        btnRealizarOperacion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRealizarOperacion.setText("Realizar Operacion");
        btnRealizarOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarOperacionMouseClicked(evt);
            }
        });
        btnRealizarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarOperacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("a:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escriba el numero con el que desea realizar la operacion");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        grupoBase.add(optHexadecimalBase);
        optHexadecimalBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optHexadecimalBase.setText("Hexadecimal");
        optHexadecimalBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optHexadecimalBaseActionPerformed(evt);
            }
        });

        grupoBase.add(optDecimalBase);
        optDecimalBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optDecimalBase.setText("Decimal");
        optDecimalBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDecimalBaseActionPerformed(evt);
            }
        });

        grupoBase.add(optBinarioBase);
        optBinarioBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optBinarioBase.setText("Binario");
        optBinarioBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBinarioBaseActionPerformed(evt);
            }
        });

        grupoBase.add(optOctalBase);
        optOctalBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optOctalBase.setText("Octal");
        optOctalBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optOctalBaseActionPerformed(evt);
            }
        });

        lblBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBaseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Transformar de:");

        grupoResultado.add(optHexadecimalResult);
        optHexadecimalResult.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optHexadecimalResult.setText("Hexadecimal");
        optHexadecimalResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optHexadecimalResultActionPerformed(evt);
            }
        });

        grupoResultado.add(optDecimalResult);
        optDecimalResult.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optDecimalResult.setText("Decimal");
        optDecimalResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDecimalResultActionPerformed(evt);
            }
        });

        grupoResultado.add(optBinarioResult);
        optBinarioResult.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optBinarioResult.setText("Binario");
        optBinarioResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optBinarioResultActionPerformed(evt);
            }
        });

        grupoResultado.add(optOctalResult);
        optOctalResult.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optOctalResult.setText("Octal");
        optOctalResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optOctalResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optHexadecimalBase)
                            .addComponent(optDecimalBase)
                            .addComponent(optBinarioBase)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(optOctalBase)
                                .addGap(62, 62, 62)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optHexadecimalResult)
                            .addComponent(optDecimalResult)
                            .addComponent(optBinarioResult)
                            .addComponent(optOctalResult))
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblBase, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRealizarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(optDecimalBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optBinarioBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optOctalBase)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optHexadecimalBase))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(optDecimalResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optBinarioResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optOctalResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optHexadecimalResult)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResultado)
                    .addComponent(lblBase))
                .addGap(56, 56, 56)
                .addComponent(btnRealizarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarOperacionMouseClicked
        String message = lblBase.getText();
        int a;  
        Long b;
        try {
            if (optDecimalBase.isSelected()) {
                a =  Integer.parseInt(lblBase.getText());

                if (optBinarioResult.isSelected()) {
                    message = Integer.toBinaryString(a);
                }
                if (optOctalResult.isSelected()) {
                    message = Integer.toOctalString(a);
                }
                if (optHexadecimalResult.isSelected()) {
                    message = Integer.toHexString(a);
                }
            }
            if (optBinarioBase.isSelected()) {
                b = Long.parseLong(lblBase.getText(), 2);
                int c = Math.toIntExact(b);

                if (optDecimalResult.isSelected()) {
                    message = c + "";
                }
                if (optOctalResult.isSelected()) {
                    message = Integer.toOctalString(c);
                }
                if (optHexadecimalResult.isSelected()) {
                    message = Integer.toHexString(c);
                }
            }
            if (optOctalBase.isSelected()) {
                b = Long.parseLong(lblBase.getText(), 8);
                int c = Math.toIntExact(b);

                if (optDecimalResult.isSelected()) {
                    message = c + "";
                }
                if (optBinarioResult.isSelected()) {
                    message = Integer.toBinaryString(c);
                }
                if (optHexadecimalResult.isSelected()) {
                    message = Integer.toHexString(c);
                }
            }
            if (optHexadecimalBase.isSelected()) {
                b = Long.parseLong(lblBase.getText(), 16);
                int c = Math.toIntExact(b);

                if (optDecimalResult.isSelected()) {
                    message = c + "";
                }
                if (optBinarioResult.isSelected()) {
                    message = Integer.toBinaryString(c);
                }
                if (optOctalResult.isSelected()) {
                    message = Integer.toOctalString(c);
                }
            }
        } catch (Exception e) {
            message = "Este numero no es valido";
        }    
        lblResultado.setText(message);
    }//GEN-LAST:event_btnRealizarOperacionMouseClicked

    private void btnRealizarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarOperacionActionPerformed

    private void optHexadecimalBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optHexadecimalBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optHexadecimalBaseActionPerformed

    private void optDecimalBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDecimalBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDecimalBaseActionPerformed

    private void optBinarioBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBinarioBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBinarioBaseActionPerformed

    private void optOctalBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optOctalBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optOctalBaseActionPerformed

    private void optMultiplicacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMultiplicacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMultiplicacion1ActionPerformed

    private void optDivision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDivision1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDivision1ActionPerformed

    private void optSuma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSuma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSuma1ActionPerformed

    private void optResta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optResta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optResta1ActionPerformed

    private void optHexadecimalResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optHexadecimalResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optHexadecimalResultActionPerformed

    private void optDecimalResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDecimalResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDecimalResultActionPerformed

    private void optBinarioResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optBinarioResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optBinarioResultActionPerformed

    private void optOctalResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optOctalResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optOctalResultActionPerformed

    private void lblBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraProgramacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculadoraProgramacion dialog = new CalculadoraProgramacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarOperacion;
    private javax.swing.JLabel equal;
    private javax.swing.ButtonGroup grupoBase;
    private javax.swing.ButtonGroup grupoResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lblBase;
    private javax.swing.JTextField lblResultado;
    private javax.swing.JRadioButton optBinarioBase;
    private javax.swing.JRadioButton optBinarioResult;
    private javax.swing.JRadioButton optDecimalBase;
    private javax.swing.JRadioButton optDecimalResult;
    private javax.swing.JRadioButton optDivision1;
    private javax.swing.JRadioButton optHexadecimalBase;
    private javax.swing.JRadioButton optHexadecimalResult;
    private javax.swing.JRadioButton optMultiplicacion1;
    private javax.swing.JRadioButton optOctalBase;
    private javax.swing.JRadioButton optOctalResult;
    private javax.swing.JRadioButton optResta1;
    private javax.swing.JRadioButton optSuma1;
    // End of variables declaration//GEN-END:variables
}
