/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfazcalculadora;

/**
 *
 * @author pamelamurillo
 */
public class CalculadoraNormal extends javax.swing.JDialog {

    /**
     * Creates new form CalculadoraNormal
     */
    public CalculadoraNormal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        optSuma.setSelected(true);
        operatorActual.setText("+");
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCalculadora = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        equal = new javax.swing.JLabel();
        lblResultado = new javax.swing.JTextField();
        segundoOperador = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        operatorActual = new javax.swing.JLabel();
        btnRealizarOperacion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        optMultiplicacion = new javax.swing.JRadioButton();
        optDivision = new javax.swing.JRadioButton();
        optSuma = new javax.swing.JRadioButton();
        optResta = new javax.swing.JRadioButton();
        primerOperador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Pamela Murillo Anchia");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        equal.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        equal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equal.setText("=");
        equal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(equal, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblResultado.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        segundoOperador.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        operatorActual.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        operatorActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operatorActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(operatorActual, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(operatorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRealizarOperacion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRealizarOperacion.setText("Realizar Operacion");
        btnRealizarOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRealizarOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarOperacionMouseClicked(evt);
            }
        });
        btnRealizarOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarOperacionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Escoga la operación que desea realizar:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escriba los dos numeros con los que desea realizar la operacion");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        grupoCalculadora.add(optMultiplicacion);
        optMultiplicacion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optMultiplicacion.setText("Multiplicación");
        optMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMultiplicacionActionPerformed(evt);
            }
        });

        grupoCalculadora.add(optDivision);
        optDivision.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optDivision.setText("División");
        optDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optDivisionActionPerformed(evt);
            }
        });

        grupoCalculadora.add(optSuma);
        optSuma.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optSuma.setText("Suma");
        optSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optSumaActionPerformed(evt);
            }
        });

        grupoCalculadora.add(optResta);
        optResta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        optResta.setText("Resta");
        optResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRestaActionPerformed(evt);
            }
        });

        primerOperador.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(optSuma)
                                    .addComponent(optResta))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(optDivision)
                                    .addComponent(optMultiplicacion))
                                .addGap(96, 96, 96))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(primerOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRealizarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(segundoOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optMultiplicacion)
                            .addComponent(optSuma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(optDivision)
                            .addComponent(optResta))))
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(primerOperador)
                    .addComponent(segundoOperador)
                    .addComponent(lblResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnRealizarOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarOperacionMouseClicked
        String message = "0";
        int result;
        int a = Integer.parseInt(primerOperador.getText());
        int b = Integer.parseInt(segundoOperador.getText());

        if (optSuma.isSelected()) {
            operatorActual.setText("+");
            result = Calculadora.suma(a, b);
            message = String.valueOf(result);
        }
        if (optResta.isSelected()) {
            operatorActual.setText("-");
            result =  Calculadora.resta(a, b);
            message = String.valueOf(result);

        }
        if (optMultiplicacion.isSelected()) {
            operatorActual.setText("*");
            result =  Calculadora.multiplicacion(a, b);
            message = String.valueOf(result);

        }
        if (optDivision.isSelected()) {
            operatorActual.setText("/");
            result =  Calculadora.division(a, b);
            if (result == 0){
                message = "Infinito";
            } else {
                message = String.valueOf(result);
            }
        }
        lblResultado.setText(message);
    }//GEN-LAST:event_btnRealizarOperacionMouseClicked

    private void btnRealizarOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarOperacionActionPerformed

    private void optMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMultiplicacionActionPerformed

    private void optDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optDivisionActionPerformed

    private void optSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optSumaActionPerformed

    private void optRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optRestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculadoraNormal dialog = new CalculadoraNormal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarOperacion;
    private javax.swing.JLabel equal;
    private javax.swing.ButtonGroup grupoCalculadora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lblResultado;
    private javax.swing.JLabel operatorActual;
    private javax.swing.JRadioButton optDivision;
    private javax.swing.JRadioButton optMultiplicacion;
    private javax.swing.JRadioButton optResta;
    private javax.swing.JRadioButton optSuma;
    private javax.swing.JTextField primerOperador;
    private javax.swing.JTextField segundoOperador;
    // End of variables declaration//GEN-END:variables
}
